development:
    sessions:
        default:
            database: stack_place_development
            hosts:
            - localhost:27017

test:
    sessions:
        default:
            database: stack_place_test
            hosts:
            - localhost:27017
production:
    sessions:
        default:
            uri: <%= ENV['MONGO_URI'] || ENV['MONGOLAB_URI'] %>